config/routes.rb
DreamShare::Application.routes.draw do
  get "static_pages/about"

  get "static_pages/landing"

  get "static_pages/home"

  get "static_pages/contact"

  root :to => 'static_pages#landing'

  resources :dreams 
  resources :emails
  

end

app/models/dream.rb
class Dream < ActiveRecord::Base
  attr_accessible :content

  validates :content, :presence => true,
  					:length => { :minimum => 4 }

  default_scope order: 'dreams.created_at DESC'
end

app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  # GET /dreams
  # GET /dreams.json
  # def index
  #   @dreams = Dream.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @dreams }
  #   end
  # end

  # # GET /dreams/1
  # # GET /dreams/1.json
  # def show
  #   @dream = Dream.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @dream }
  #   end
  # end

  # GET /dreams/new
  # GET /dreams/new.json
  def new
    @dream = Dream.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dream }
    end
  end

  # # GET /dreams/1/edit
  # def edit
  #   @dream = Dream.find(params[:id])
  # end

  # POST /dreams
  # POST /dreams.json
  def create
    @dream = Dream.new(params[:dream])

    respond_to do |format|
      if @dream.save
        format.html { redirect_to root_path, notice: 'Dream was successfully created.' }
        format.json { render json: @dream, status: :created, location: @dream }
      else
        format.html { render action: "new" }
        format.json { render json: @dream.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PUT /dreams/1
  # # PUT /dreams/1.json
  # def update
  #   @dream = Dream.find(params[:id])

  #   respond_to do |format|
  #     if @dream.update_attributes(params[:dream])
  #       format.html { redirect_to @dream, notice: 'Dream was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @dream.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /dreams/1
  # # DELETE /dreams/1.json
  # def destroy
  #   @dream = Dream.find(params[:id])
  #   @dream.destroy

  #   respond_to do |format|
  #     format.html { redirect_to dreams_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  # GET /emails
  # GET /emails.json
  # def index
  #   @emails = Email.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @emails }
  #   end
  # end

  # GET /emails/1
  # GET /emails/1.json
  # def show
  #   @email = Email.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @email }
  #   end
  # end

  # GET /emails/new
  # GET /emails/new.json
  def new
    @email = Email.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @email }
    end
  end

  # # GET /emails/1/edit
  # def edit
  #   @email = Email.find(params[:id])
  # end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(params[:email])

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, notice: 'Email was successfully created.' }
        format.json { render json: @email, status: :created, location: @email }
      else
        format.html { render action: "new" }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PUT /emails/1
  # # PUT /emails/1.json
  # def update
  #   @email = Email.find(params[:id])

  #   respond_to do |format|
  #     if @email.update_attributes(params[:email])
  #       format.html { redirect_to @email, notice: 'Email was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @email.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /emails/1
  # # DELETE /emails/1.json
  # def destroy
  #   @email = Email.find(params[:id])
  #   @email.destroy

  #   respond_to do |format|
  #     format.html { redirect_to emails_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def landing
  	@dream = Dream.new
  	#@dreams = Dream.all.paginate(page: params[:page])  
  	@dream_items = Dream.paginate(page: params[:page])
  end

  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def random_back_img
		images = ["assets/Cloud1-web.jpg", "assets/Water-web.jpg", "assets/Ocean3-web.jpg", "assets/SunBoat2-web.jpg"]
		images[rand(images.size)]
	end

end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dreams/_form.html.erb
<%= form_for(@dream) do |f| %>
  <% if @dream.errors.any? %>"
      <div id="error_explanation">
        <h2><%= pluralize(@dream.errors.count, "error") %> prohibited this dream from being saved:</h2>
  
        <ul>
        <% @dream.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <!--<%= f.label :content, 'Dream' %><br/> -->
      <!-- :class => "form-control input-lg", -->
      
      <%= f.text_area :content, :class => "content-input", :placeholder => "I Have A Dream...", size: "30x1" %></span>
    </div>

  <div class="actions">
    <%= f.submit "Share Dream", :class => "btn btn-success bt-lg"%>
  </div>
<% end %>

app/views/dreams/index.html.erb
<h1>Listing dreams</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dreams.each do |dream| %>
  <tr>
    <td><%= link_to 'Show', dream %></td>
    <td><%= link_to 'Edit', edit_dream_path(dream) %></td>
    <td><%= link_to 'Destroy', dream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dream', new_dream_path %>

app/views/dreams/new.html.erb
<h1>New dream</h1>

<%= render 'form' %>

<%= link_to 'Back', dreams_path %>

app/views/layouts/_google-analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44934389-1', 'dreamtm.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DreamTeam</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- The viewport allows mobile devices and tablets to view to website at a reasonable scale -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- The link below contains the fonts this website uses -->
  <link href='http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600' rel='stylesheet'>
  <!-- The code below chooses the background image and sets it to cover the fullscreen. More info in the app/helpers/application_helper.rb -->
  <style type="text/css">
  	html {
			background: url(<%= random_back_img %>) no-repeat center center fixed;
			-webkit-background-size: cover;
			-moz-background-size: cover;
			-o-background-size: cover;
			background-size: cover;
		}
	</style>
</head>
<body>

<!-- The yield renders the page the user is looking at. Since the only page the user can see on this website is the landing page, the yield only renders the landing page. If I were to create a button that links to another page under the same domain name, the yield would render that page. In very simple words, the application.html.erb is included in every page of the website. -->
<%= yield %>

<!-- It's important to note that anything starting with a < % in a embedded ruby file (.erb) means that the code in the arrow thingys is actually ruby code. In this case, the code checks to see if the Rails environment is in production. If the Rails environment is in production (as in if its live), then it will execute the following line. All < % must be closed with an %>. -->

<% if Rails.env == "production" %>
  <!-- This partial renders code from the app/views/layout/_google-analytics.html.erb . Find out more info about google anaylitics in that file -->
  <%= render "layouts/google-analytics" %>
<% end %>
<!-- The if conditional must also have an < % end % > -->
</body>
</html>

app/views/shared/_dream_item.html.erb
<!--<ul id="<%= dream_item.id %>"> -->
<div class="dream-item">
	<p class="content">
		<!-- <span class="content"><%= dream_item.content %></span> -->
		<%= dream_item.content %></p>
		<!-- <span class="timestamp">
			Shared <%= time_ago_in_words(dream_item.created_at) %> ago.
		</span> -->
		<p class="timestamp">
			Shared <%= time_ago_in_words(dream_item.created_at) %> ago.
		</p>
	<!-- </p> -->
</div>

app/views/shared/_feed.html.erb
<% if @dream_items.any? %>
	<div class="dream-container">
		<%= render partial: 'shared/dream_item', collection: @dream_items %>
	</div>
	<%= will_paginate @dream_items %>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/static_pages/landing.html.erb
<!--  The Tutorial Starts Here   -->

<!-- As of right now, this website only consists of one webpage, which is the DreamTeam landing page, which is also the main page at this moment. Head over to the routes.rb for more info -->

<!-- Below, you will see a couple of divs with some classes. While you do not see any css code for the container class and the row class, it's obvious it has some styling, and that would be due to the bootstrap plugin developed by twitter. Its best to look up the bootstrap documentation there. -->
<div class="container">
	<div class="row">

		<!-- However, there is css code for the panel class. You can find the css code for the panel class and the margin-base-vertical class in app/assets/stylesheets/custom.css.scss -->
		<div class="col-md-6 col-md offset-3 panel panel-default">
			<h1 class="margin-base-vertical">DreamTeam</h1>
			<h2>I Have A Dream...</h2>
			<p class="about">Everyone has a dream. Today, nearly everyone is educated, and it is easy as ever to connect and communicate with others. We all have the power to do what we dream, and it's getting easier to find others that share the same dream. My dream is to be able to use the skills I continuously pick up to help others and leave the world better than when I found it.</p>

			<h2>What's yours?</h2>

			<div class="margin-base-vertical">
				<!-- This is a partial, which means that the code in the file app/views/dreams/_form.html.erb will render here. It is important to place code into partials so that you can just call the partial instead of writing the form code everytime you need it. It helps condense code and keep it neat! -->
				<%= render "dreams/form" %>
			</div>

			<div class="margin-base-vertical">
				<h2>Dreams Around the World</h2>
				<!-- This partial calls for code in the app/views/shared/_feed.html.erb -->
				<%= render 'shared/feed' %>
			</div>
			
		</div>
	</div>
</div>

<!-- It's important to note that this whole file is being rendered in the app/views/application.html.erb file. -->